name: ${PROJECT_NAME}-dev
services:
  symfony:
    volumes:
      - .:/var/www
      - /var/www/var
      - /var/www/vendor
      - extensions:/root/.vscode-server/extensions
  # mailer:
  #     image: axllent/mailpit
  #     ports:
  #         - "1025"
  #         - "8025"
  #     environment:
  #         MP_SMTP_AUTH_ACCEPT_ANY: 1
  #         MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  extensions:
